version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build:
    executor:
      name: node/12.16.3
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build

  build_artifact:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run build
            - run: mv dist $APP_NAME
            - run: tar cvf $APP_NAME.tar.gz $APP_NAME
            - run: mv $APP_NAME.tar.gz artifacts
      - store_artifacts:
          path: artifacts/**

workflows:
    build:
      jobs:
        - build_artifact
