version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  build_artifact:
    executor:
      name: node/default
      tag: 12.16.3
    steps:
      - checkout
      - node/install-packages:
           cache-path: ~/project/node_modules
           override-ci-command: npm install
      - run: npm run build
      - run: mkdir artifacts
      - run: mv dist $APP_NAME
      - run: tar cvf $APP_NAME.tar.gz $APP_NAME
      - run: mv $APP_NAME.tar.gz artifacts
      - run: ls artifacts
      - run: ls artifacts/**
      - store_artifacts:
          path: artifacts

workflows:
    build:
      jobs:
        - build_artifact
